### ISSUE TITLE
Enable contact form

### ISSUE THREAD

**Issue by Sergiiivzhenko** [web2easy/OctoberCMS-Juicy-Theme#2]
How can I enable this Vuejs code in my project?
jQuery(document).ready(function(t) {
        t("[data-form-phone-field]").mask("+7 (999) 999-99-99"), t("[data-form-time-field]").mask("99:99"), t("[data-form-btn]").click(function() {
            var e = t(this),
                i = t(this).parents("[data-form]"),
                o = i.find("[data-form-status]"),
                a = {},
                n = e.text(),
                s = i.attr("data-form-template"),
                r = i.attr("data-form-recipient"),
                l = i.attr("data-reachGoal"),
                c = ["Пожалуйста, укажите номер телефона", "Спасибо, сообщение отправлено", "При отправке сообщения возникли проблемы. Пожалуйста, отправьте письмо на ящик " + r];
            return i.find("*[required]").each(function() {
                t(this).removeAttr("data-form-field-invalid"), "" != t(this).val() && t(this).val() != t(this).attr("placeholder") || (t(this).attr("data-form-field-invalid", ""), i.find("input[data-form-field-invalid], textarea[data-form-field-invalid]").addClass("shake animated"), setTimeout(function() {
                    i.find("input[data-form-field-invalid], textarea[data-form-field-invalid]").removeClass("shake animated")
                }, 1e3))
            }), i.find("[data-form-field-invalid]").length ? (o.html(c[0]).slideDown(500), !1) : (i.find("input, textarea, select").each(function(e) {
                var i = t(this).attr("name"),
                    o = t(this).attr("placeholder") || t(this).prev().html();
                o = t.trim(o.replace(/[:*]/g, "")), a[i] = {
                    label: o,
                    value: t(this).val()
                }
            }), t.ajax({
                url: "/themes/" + s + "/assets/forms/send-form.php",
                type: "POST",
                data: {
                    send: "do",
                    to: r,
                    subj: i.attr("title"),
                    data: a
                },
                beforeSend: function() {
                    e.text("Отправка...")
                },
                success: function(t) {
                    var a = parseInt(t);
                    return e.text(n), o.html(c[a]).slideUp(500), 1 == a && (i.attr("data-form-success", ""), i.find("input, textarea, select").val("")), yaCounter39444945.reachGoal(l), !0
                },
                error: function(t, e, i) {
                    alert(e + "," + i + "," + t.responseText)
                }
            }), !1)
        })
    })

Can you please share how this code works, and what should be modified from default template?
Thanks in advance.

**Comment by alex-lit** [comment]
@Sergiiivzhenko Привет, в шаблоне компонент формы не предусмотрен, нужно либо писать самому либо использовать одно из готовых решений с магазина расширений OctoberCMS.

**Comment by Sergiiivzhenko** [comment]
Спасибо, а зачем тогда этот кусок кода?

**Comment by alex-lit** [comment]
Это обработчик форм на jQuery, он в шаблоне не используется. Где он присутствует в сборке? Надо бы вырезать.

**Comment by Sergiiivzhenko** [comment]
Ок, теперь понял, спасибо за ответ. Можно закрыть этот issue.
