### ISSUE TITLE
How to add a contact form?

### ISSUE THREAD

**Issue by ffuentese** [web2easy/OctoberCMS-Juicy-Theme#4]
I'd like to add a contact form using one of the plugins but I don't know how to integrate them. I tried using one of the widgets but they are not compatible with components and when trying to add them from the main page it doesn't render properly. 

So far I tried Magic Forms and Custom Forms.

**Comment by alex-lit** [comment]
Any third-party component can be inserted to the `home.htm` page following components documentation.

Example

```twig
...template code

{# YOUR_FORM #}
{% component 'YOUR_FORM' %}

{# Site footer #}
{% if this.theme.site_footer_enable %}
    <site-footer
        company          = "{{ this.theme.site_footer_company }}"
        background-color = "{{ this.theme.site_footer_background_color }}"
    ></site-footer>
{% endif %}
```

**Comment by ffuentese** [comment]
Yeah but when I do that the form appears beneath the component and can't really be used. This happened to me with every plugin I tried.

https://imgur.com/DEmna1j

**Comment by alex-lit** [comment]
Can you provide a link to the project or console error messages?

**Comment by ffuentese** [comment]
It's [here](https://cabildos.org)

**Comment by alex-lit** [comment]
Add this style:

```css
.flexiContactForm {
  position: relative;
}
```

**Comment by ffuentese** [comment]
Thanks, now I got it.
