### ISSUE TITLE
Adding new components

### ISSUE THREAD

**Issue by ffuentese** [web2easy/OctoberCMS-Juicy-Theme#5]
Basically it. I was trying to find the main file where all components are declared and couldn't find it.

What's the right way to create a custom component? I guess someone has to modify theme.yaml to add the component but will that be enough? What about adding a component that includes plugins or server code?

**Comment by alex-lit** [comment]
You can easily add new components as it described in the OctoberCMS documentation.

**Comment by ffuentese** [comment]
I mean this is made with Vue but Vue files aren't available.

**Comment by alex-lit** [comment]
`Vue` components available from [source](https://github.com/alex-lit/OctoberCMS-Juicy-Theme/tree/master/src) code of repository. To add a new `vue` component, you need to rebuild template from the source files. 

But you can create your own OctoberCMS components (partial with `twig` template) without using vue.js and easily integrate them into template.
